# Generated by Django 2.1.1 on 2018-11-01 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appserver', '0002_auto_20181021_1123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='userchild',
            options={'managed': False},
        ),
    ]
