# Generated by Django 2.1.1 on 2018-11-01 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appserver', '0003_auto_20181101_0931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'managed': True},
        ),
    ]
